configfile: "config/config.yaml"


rule produce_kage_benchmark_report:
  input:
    gpu_kmer_mapper="temp/benchmarks/gpu_kmer_mapper.txt",
    cpu_kmer_mapper="temp/benchmarks/cpu_kmer_mapper.txt",
    kage="temp/benchmarks/kage.txt"
  output:
    report="benchmark_report.html"
  shell:
    """
    python create_benchmark_report.py \
        {input.gpu_kmer_mapper} {input.cpu_kmer_mapper} {input.kage}
    """


rule run_kage:
  input:
    counts="temp/cpu_kmer_counts.npy",
    kmer_index="{config[test_index_minimal]}",
    variants="{config[test_vars]}"
  output:
    vcf="temp/genotypes.vcf"
  benchmark:
    "temp/benchmarks/kage.txt"
  shell:
    """
    kage genotype \
        -c {input.counts} \
        -i {input.kmer_index} \
        -k {config[kmer_size]} \
        -a 15 \
        -t {config[n_threads_few]} \
        -b True \
        -o {output.vcf} \
        --variants {input.variants} \
        --do-not-write-genotype-likelihoods True
    """


rule run_gpu_kmer_mapper:
  input:
    kmer_index="{config[test_index_vars_w_revcomps]}",
    reads="{config[test_reads]}"
  output:
    counts="temp/gpu_kmer_counts.npy",
  benchmark:
    "temp/benchmarks/gpu_kmer_mapper.txt"
  shell:
    """kmer_mapper map \
        -i {input.kmer_index} \
        -f {input.reads} \
        -t {config[n_threads_few]} \
        -k {config[kmer_size]} \
        -c {config[gpu_chunk_size]} \
        -o {output.counts} \
        --gpu True
    """


rule run_cpu_kmer_mapper:
  input:
    kmer_index="{config[test_index_vars_w_revcomps]}",
    reads="{config[test_reads]}"
  output:
    counts="temp/cpu_kmer_counts.npy",
  benchmark:
    "temp/benchmarks/cpu_kmer_mapper.txt"
  shell:
    """kmer_mapper map \
        -i {input.kmer_index} \
        -f {input.reads} \
        -t {config[n_threads_few]} \
        -k {config[kmer_size]} \
        -c {config[cpu_chunk_size]} \
        -o {output.counts}
    """


rule unzip_fastas:
  input:
    "{config[test_reads_zipped]}"
  output:
    "{config[test_reads]}"
  shell:
    """
    gunzip *.fa.gz
    """


rule download_files:
  output:
    "{config[test_reads_zipped]}",
    "{config[test_index_minimal]}",
    "{config[test_index_vars_w_revcomps]}",
    "{config[test_index_vars_wo_revcomps]}",
    "{config[test_vars]}"
  shell:
    """
    mkdir temp/
    mkdir temp/benchmarks/
    wget -P temp/ {config[test_reads_zipped_dl_link]}
    wget -P temp/ {config[test_index_minimal_dl_link]}
    wget -P temp/ {config[test_index_vars_w_revcomps_dl_link]}
    wget -P temp/ {config[test_index_vars_wo_revcomps_dl_link]}
    wget -P temp/ {config[test_vars_dl_link]}
    """
